services:
  discordbot:
    container_name: Discord-TTS-Bot
    build:
      context: ./
    restart: on-failure
    healthcheck:
      test: [
        "CMD-SHELL",
        "curl -f http://localhost:8080/healthcheck -A 'curl/some-version (+healthcheck)'"
      ]
      interval: 15s
      timeout: 5s
      retries: 2
      start_period: 10s
    env_file:
      - ${envFile}
    # Sequelize needs access to the host mysqld
    extra_hosts:
      - "host.docker.internal:host-gateway"
    security_opt:
      - no-new-privileges
