name: Docker Deployment

on:
  push:
    branches: [ master ]
  workflow_dispatch:

concurrency:
  group: deployment
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: mainserver-pez
    env:
      envFile: ${{ secrets.ENV_FILE }}
      HC_PORT: ${{ secrets.HC_PORT }}

    steps:
      - uses: actions/checkout@v3

      - name: Update containers
        run: docker compose pull

      - name: Build application
        run: docker compose build

      - name: Spin up containers
        run: docker compose up -d